language: node_js
node_js:
- '9'
before_install:
- npm install -g npm
install:
- npm install
script:
- tsc
- webpack
deploy:
  provider: heroku
  api_key:
    secure: t8apvFPT4jO80u2tfjFLFnGlx4fD2cGEEIs5+SWDRfFmkxP2ubcS+VfdNgdwagJc8HHOc/qVngcJowxO5Byt48MZFTt8+loM4m5O5ejBWA1be6eSsX2a0JAgmd4h80rvMqFKFxFdUdF22lI9kGmD12KKXne/IMIB1rHyCXR9mpJBQMXFse8/inUdeg5Ad1tYz/wvIMSLcbVd790cl9F5B/qUXMaU5RiUCNA1oGXrXXg6QNck933ZItLz3ei6PIy0PG+mmane+L9huSN/ZPBGc3MgiGHD1n0b2DWOvyALvFfD+vxjTxAYTmzDLujjMXHJkAYMF6shhavnjAh8zR8FYbg+IgYgNoCuEJip/fflXF9tLr20XUBgEKbgujQ04r6e3hl0vc2kqIRvSSPQEBM8jCCOjZiA8fcj3smAzN+kkMME4mSbJAdUoiCNxC1cm1Ag1xiz9YWg3iTt3anOX9W772XMe8GrHwlHifuHnOEg6fUvFV4wEHTYcqfC20xQa5+PZ4640z/vCAs6h/+WoHwgjszzR1FeEZYUvn/D0KqLx+6Nh0oAcvmcZ/tO+MCq3mxstGisWJxCB/kcbe/rOMIT2TfEN52O6wAzl+5nf+KToBRpFFRNckLyFobOLpgi/65Xi03Z31fyrOnim7j+xxMBQQxi8CPaYHGysKPRGL+79rk=
  app: judahh
  on:
    repo: Judahh/judahh
